name: cb
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - graphviz=2.50.0
  - ipython=8.4.0
  - joblib=1.4.0
  - jpeg=9e
  - jsonschema=4.21.1
  - loguru=0.5.3
  - lxml=4.8.0
  - m2r=0.3.1
  - matplotlib=3.5.2
  - numpy=1.23.3
  - openjpeg=2.4.0
  - pandas=1.2.4
  - pip=22.1.2
  - pydata-sphinx-theme=0.13.3
  - pydicom=2.3.0
  - pyodbc=4.0.34
  - pytest=7.1.2
  - python==3.9.15
  - pytorch==2.1.2=cpu_mkl_py39h2154f18_101
  - reportlab=3.5.67
  - requests=2.28.1
  - scikit-image=0.19.2
  - scipy=1.10.0
  - seaborn=0.12.2
  - sphinx-copybutton=0.5.0
  - sphinx-design=0.4.1
  - sphinxcontrib-autoprogram=0.1.5
  - svglib=1.4.1
  - torchvision==0.16.2=py39_cpu
  - tqdm=4.64.0
  - typing-extensions=4.4.0
  - ipykernel
  - openssl=1.1.1w
  - openpyxl=3.1.2
  - pip:
    - oct-converter==0.6.2
    - opencv-python==4.5.5.64
    - paramiko==3.2.0
    - pillow==9.4.0
    - pylibjpeg==1.4.0
    - pylibjpeg-libjpeg==1.3.4
    - pylibjpeg-openjpeg==1.3.2
    - pylibjpeg-rle==1.3.0
    - pylint==2.15.9
    - sphinx==6.2.1
